apiVersion: v1
items:
- apiVersion: v1
  data:
    postgres_password: c1oudc0w
    postgres_user: admin
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    name: postgres-config
    namespace: default
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    name: postgres-pv-claim
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 32Gi
    volumeMode: Filesystem
  status:
    phase: Pending
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      app: postgres
    name: postgres
  spec:
    progressDeadlineSeconds: 2147483647
    replicas: 1
    revisionHistoryLimit: 2147483647
    selector:
      matchLabels:
        app: postgres
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: postgres
      spec:
        containers:
        - env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                key: postgres_user
                name: postgres-config
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                key: postgres_password
                name: postgres-config
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          image: postgres
          imagePullPolicy: Always
          name: postgres
          ports:
          - containerPort: 5432
            name: postgres
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-storage
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: postgres
  spec:
    internalTrafficPolicy: Cluster
    ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      app: postgres
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata: {}
